# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: sel-kham <sel-kham@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/05/20 18:57:41 by sel-kham          #+#    #+#              #
#    Updated: 2022/05/20 19:48:25 by sel-kham         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Colrs
RED := \033[0;31m
WHITE := \033[0;37m
GREEN := \033[0;32m
BLUE := \033[0;34m

# Just playing
PHILO := $(shell cat ascii-art.ans)


CFLAGS := -Wall -Wextra -Werror
NAME := philo

all:
	@cat ascii-art.ans